### ISSUE TITLE
Review of architecture documents

### ISSUE THREAD

**Issue by rufuspollock** [rufuspollock-okfn/textus#4] opened 2012-04-11 08:13 UTC
This is a placeholder issue to discuss these pieces of documentation:
- Architecture overview: https://github.com/okfn/textus/blob/master/docs/architecture_overview.md
- Text rendering: https://github.com/okfn/textus/blob/master/docs/text_rendering.md

**Comment by rufuspollock** [comment] 2012-04-11 08:14
Having read the documentation I'd like to register a strong +1 -- these are both excellent.

I think it would be useful to see, asap, example (or actual) code implementing things like:
- Importing of a standard HTML document and its conversion to the text + annotation form
- Import of a plain text document (in, say, markdown) and similar conversion

**Comment by tomoinn** [comment] 2012-04-11 08:48
I was chatting with Sam Leon yesterday about importing - there's an example of importing plain text (without markup) at https://github.com/okfn/textus/blob/master/src/tools/import-text.js which is obviously trivial but was used to generate the test data (semantic annotations added manually)

Sam mentioned the Text Encoding Initiative as a useful import target - http://www.tei-c.org/index.xml, I guess HTML would be useful though to allow us to import content already in OpenShakespeare and friends?

**Comment by rufuspollock** [comment] 2012-05-12 16:16
Yes +1 on HTML - I've created #9 for this.

Could we get some proper documentation (even if just a few lines) in README on docs on how this works. Also let's switch to sphinx asap - #10.

**Comment by tomoinn** [comment] 2012-05-14 08:52
There's a document in /docs on the import process. I'll move these to sphinx when I have time to reboot into the operating system which doesn't support half the hardware in either of my machines (linux, because you didn't want that soundcard / camera / trackpad anyway...)

**Comment by noelmas** [comment] 2012-07-19 09:34
Duplicate of #3

**Closed as completed** 2013-12-22 18:39 UTC
Labels: documentation, textus-v1-deprecated-issues
