### ISSUE TITLE
Print a Text with Annotations

### ISSUE THREAD

**Issue by AndrewMagliozzi** [rufuspollock-okfn/textus#38] opened 2012-08-14 21:12 UTC
## Print a Text with Annotations

It is not easy to read an entire book on a computer screen, and I believe many users would like the option to print a given text (page, section, chapter, or book) with annotations for off-line reading.  

Ideally there would be some mechanism for selecting pages / sections as well as some granularity of annotations (such as those from certain people only) for export to PDF.  Annotations will ideally appear in the margins, but end notes for each section would suffice as well.  Here's an example of our work in the latter format:

Macbeth 
http://dl.dropbox.com/u/15975779/Macbeth%20ebook.pdf

If anyone else would like to work on this, please ping me.  I'd be glad to help.

**Comment by tomoinn** [comment] 2012-08-19 12:14
Duplicate of https://github.com/okfn/textus/issues/39

**Closed as completed by tomoinn** 2012-08-19 12:14 UTC
